version: '3'

volumes:
  kanban-data:
  pgadmin-data:
  prometheus-data:
  grafana-data:
  nginx-logs-data:

services:

  kanban-postgres:
    image: postgres:9.6-alpine
    container_name: kanban-postgres
    volumes:
      - kanban-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  
  kanban-app:
    build: ./taskmanagerapp/kanban-app/
    container_name: kanban-app
    ports: 
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_SERVER=${DB_SERVER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    links:
      - "kanban-postgres"
  
  kanban-ui:
    build: ./taskmanagerapp/kanban-ui/
    container_name: kanban-ui
    ports:
      - "4200:80"
    links:
      - "kanban-app"
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - kanban-postgres
    ports:
      - "5050:80"
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - nginx-logs-data:/var/log/nginx
    links:
      - kanban-ui
      - kanban-app
      - pgadmin
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: 'true'
        fluentd-address: localhost:24224
        tag: nginx
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - cadvisor:cadvisor
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    restart: always
  
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    expose:
      - 8081
    ports:
      - 8081:8081
    command:
    - '-port=8081'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      # If using WSL2
      # for more: https://github.com/google/cadvisor/issues/2648
      - /mnt/windows_docker/:/rootfs/var/lib/docker:ro
